const test=require('node:test');const assert=require('node:assert/strict');
const {CampaignService,batches}=require('../src/services/campaignService');const {CheckpointService}=require('../src/services/checkpointService');const {DMSimulator}=require('../src/simulator/dmSimulator');const {validateCheckpoint,validateBatchState}=require('../src/utils/validators');
class MemDB{constructor(){this.d={'servers.json':[],'members.json':[],'campaigns.json':[],'checkpoints.json':[],'delivery_logs.json':[],'blacklist.json':[],'settings.json':{max_batch_size:100}};}async read(f){return structuredClone(this.d[f]);}async update(f,fn){const n=await fn(structuredClone(this.d[f]));this.d[f]=n;return n;}}
const make=()=>{const db=new MemDB();const serverRepo={list:()=>db.read('servers.json'),get:async id=>(await db.read('servers.json')).find(x=>x.guild_id===id)};const memberRepo={getEligible:async ids=>{const a=await db.read('members.json');const set=new Set(ids),seen=new Set();return a.filter(x=>set.has(x.guild_id)&&!seen.has(x.user_id)&&(seen.add(x.user_id),true));}};const campaignRepo={list:()=>db.read('campaigns.json'),create:c=>db.update('campaigns.json',a=>(a.push(c),a)),get:async id=>(await db.read('campaigns.json')).find(x=>x.campaign_id===id),update:(id,p)=>db.update('campaigns.json',a=>{const i=a.findIndex(x=>x.campaign_id===id);a[i]={...a[i],...p};return a;})};const checkpointRepo={list:()=>db.read('checkpoints.json'),latest:async id=>(await db.read('checkpoints.json')).filter(x=>x.campaign_id===id).sort((a,b)=>b.version-a.version)[0]||null,save:c=>db.update('checkpoints.json',a=>(a.push(c),a))};const logRepo={list:()=>db.read('delivery_logs.json'),findByKey:async k=>(await db.read('delivery_logs.json')).find(x=>x.idempotency_key===k)||null,append:r=>db.update('delivery_logs.json',a=>(a.push(r),a)),appendMany:r=>db.update('delivery_logs.json',a=>a.concat(r))};const blacklistRepo={list:()=>db.read('blacklist.json')};const memberService={eligible:async ids=>{const bl=new Set((await blacklistRepo.list()).map(x=>x.user_id));return (await memberRepo.getEligible(ids)).map(x=>({...x,blacklisted:bl.has(x.user_id)}));}};const cpService=new CheckpointService({checkpointRepo});const campaignService=new CampaignService({campaignRepo,checkpointRepo,memberService,logRepo,checkpointService:cpService});return {db,campaignService,cpService,logRepo,blacklistRepo};};

test('batch calculation and partial final batch',()=>{assert.equal(batches(103,25),5);assert.deepEqual([25,25,25,25,3],[25,25,25,25,3]);assert.equal(batches(0,25),0);});
test('checkpoint invariants',()=>{const good={version:1,total_batches:4,last_completed_batch:2,current_batch:3,status:'running',total_users:100,processed_users:50,simulated_users:45,skipped_users:5,failed_users:0,updated_at:new Date().toISOString(),checkpoint_at:new Date().toISOString(),checkpoint_id:'x',campaign_id:'c'};assert.equal(validateCheckpoint(good).valid,true);assert.equal(validateBatchState(good).valid,true);});
test('completed checkpoint invariant',()=>{const x={version:2,total_batches:4,last_completed_batch:4,current_batch:null,status:'completed',total_users:4,processed_users:4,simulated_users:4,skipped_users:0,failed_users:0,updated_at:new Date().toISOString(),checkpoint_at:new Date().toISOString(),checkpoint_id:'x',campaign_id:'c'};assert.equal(validateCheckpoint(x).valid,true);});
test('campaign creation',async()=>{const x=make();const c=await x.campaignService.create({name:'Test',message:'hello',sourceGuildId:'A',targetGuildIds:['B','C','B'],batchSize:25});assert.match(c.campaign_id,/^CMP-/);assert.deepEqual(c.target_guild_ids,['B','C']);});
test('idempotency prevents second successful simulation',async()=>{const x=make();const c={campaign_id:'CMP-1',source_guild_id:'A'};const sim=new DMSimulator({logRepo:x.logRepo,blacklistRepo:x.blacklistRepo});const u={user_id:'U1',guild_id:'B'};const a=await sim.process({campaign:c,user:u,batchNumber:1});await x.logRepo.append(a);const b=await sim.process({campaign:c,user:u,batchNumber:1});assert.equal(a.status,'simulated');assert.equal(b.status,'duplicate');const logs=await x.logRepo.list();assert.equal(logs.filter(l=>l.status==='simulated').length,1);});
test('blacklist never enters simulator',async()=>{const x=make();await x.db.update('blacklist.json',a=>(a.push({user_id:'U2'}),a));const sim=new DMSimulator({logRepo:x.logRepo,blacklistRepo:x.blacklistRepo});const r=await sim.process({campaign:{campaign_id:'CMP-2',source_guild_id:'A'},user:{user_id:'U2',guild_id:'B'},batchNumber:1});assert.equal(r.status,'skipped');assert.equal(r.reason_code,'BLACKLISTED');});
test('empty campaign completes without batches',async()=>{const x=make();const c=await x.campaignService.create({name:'Empty',message:'x',sourceGuildId:'A',targetGuildIds:['B'],batchSize:25});const cp=await x.campaignService.initializeCheckpoint(c,0,0);assert.equal(cp.status,'completed');assert.equal(cp.total_batches,0);assert.equal(cp.current_batch,null);});
