const ISO = (v) => typeof v === 'string' && !Number.isNaN(Date.parse(v));
function result(errors) { return { valid: errors.length === 0, errors }; }
function validateCampaign(c) {
  const e=[]; if(!c?.campaign_id) e.push('campaign_id is required'); if(!c?.name) e.push('name is required'); if(!Array.isArray(c?.target_guild_ids)) e.push('target_guild_ids must be an array'); if(typeof c?.batch_size!=='number'||c.batch_size<1) e.push('batch_size must be a positive number'); if(!ISO(c?.created_at)||!ISO(c?.updated_at)) e.push('invalid timestamps');
  return result(e);
}
function validateCheckpoint(c) {
  const e=[]; if(!c?.checkpoint_id||!c?.campaign_id) e.push('checkpoint_id and campaign_id are required'); if(!Number.isInteger(c?.version)||c.version<1) e.push('version must be a positive integer'); if(!Number.isInteger(c?.total_batches)||c.total_batches<0) e.push('invalid total_batches'); if(!Number.isInteger(c?.last_completed_batch)||c.last_completed_batch<0||c.last_completed_batch>c.total_batches) e.push('invalid last_completed_batch'); if(c.status==='completed' && (c.last_completed_batch!==c.total_batches || c.current_batch!==null)) e.push('completed checkpoint has invalid batch state'); if(['running','recovering'].includes(c.status) && c.total_batches>0 && c.current_batch!==c.last_completed_batch+1) e.push('active checkpoint must satisfy current_batch = last_completed_batch + 1'); for(const k of ['total_users','processed_users','simulated_users','skipped_users','failed_users']) if(!Number.isInteger(c?.[k])||c[k]<0) e.push(`${k} must be non-negative integer`); if(c.processed_users < c.simulated_users + c.skipped_users + c.failed_users) e.push('processed_users cannot be less than terminal outcome counters'); if(!ISO(c?.updated_at)||!ISO(c?.checkpoint_at)) e.push('invalid checkpoint timestamps'); return result(e);
}
function validateDeliveryRecord(d) { const e=[]; if(!d?.delivery_id||!d?.campaign_id||!d?.user_id) e.push('delivery_id, campaign_id and user_id are required'); if(!['queued','processing','simulated','skipped','failed','duplicate'].includes(d.status)) e.push('invalid delivery status'); if(!d.idempotency_key) e.push('idempotency_key is required'); if(!ISO(d.created_at)||!ISO(d.updated_at)) e.push('invalid timestamps'); return result(e); }
function validateCampaignState(c) { const allowed=['draft','preview','running','paused','cancelling','cancelled','completed','failed','recovering']; return result(allowed.includes(c?.status)?[]:[`invalid campaign status: ${c?.status}`]); }
function validateBatchState({last_completed_batch,total_batches,current_batch,status}) { const e=[]; if(last_completed_batch<0||last_completed_batch>total_batches) e.push('batch counters out of range'); if(['running','recovering'].includes(status)&&total_batches>0&&current_batch!==last_completed_batch+1) e.push('active campaign batch invariant violated'); if(status==='completed'&&(last_completed_batch!==total_batches||current_batch!==null)) e.push('completed campaign batch invariant violated'); return result(e); }
module.exports={validateCampaign,validateCheckpoint,validateDeliveryRecord,validateCampaignState,validateBatchState};
