const {Client,GatewayIntentBits,Collection}=require('discord.js');
const config=require('./config/config');const logger=require('./utils/logger');
const {GitHubDatabase}=require('./database/githubDatabase');const {ServerRepo}=require('./database/repositories/serverRepo');const {MemberRepo}=require('./database/repositories/memberRepo');const {CampaignRepo}=require('./database/repositories/campaignRepo');const {CheckpointRepo}=require('./database/repositories/checkpointRepo');const {LogRepo}=require('./database/repositories/logRepo');
const {ServerService}=require('./services/serverService');const {MemberService}=require('./services/memberService');const {CampaignService}=require('./services/campaignService');const {CheckpointService}=require('./services/checkpointService');const {RecoveryService}=require('./services/recoveryService');const {QueueService}=require('./services/queueService');const {AnalyticsService}=require('./services/analyticsService');const {DMSimulator}=require('./simulator/dmSimulator');const {createDashboard}=require('./dashboard/server');
const promoFiles=['create','preview','start','pause','resume','cancel','recover','status','history'];const serverFiles=['list','stats'];const adminFiles=['settings','blacklist'];
function loadCommands(){const c=new Collection();for(const n of promoFiles)c.set(`promo:${n}`,require(`./commands/promo/${n}`));for(const n of serverFiles)c.set(`server:${n}`,require(`./commands/server/${n}`));for(const n of adminFiles)c.set(`admin:${n}`,require(`./commands/admin/${n}`));return c;}
async function main(){const db=new GitHubDatabase(config);await db.init();const serverRepo=new ServerRepo(db),memberRepo=new MemberRepo(db),campaignRepo=new CampaignRepo(db),checkpointRepo=new CheckpointRepo(db),logRepo=new LogRepo(db);const blacklistRepo={list:()=>db.read('blacklist.json')};const serverService=new ServerService({serverRepo,memberRepo});const memberService=new MemberService({memberRepo,blacklistRepo});const checkpointService=new CheckpointService({checkpointRepo});const campaignService=new CampaignService({campaignRepo,checkpointRepo,memberService,logRepo,checkpointService});const simulator=new DMSimulator({logRepo,blacklistRepo});const queueService=new QueueService({campaignService,memberService,logRepo,checkpointService,simulator,config});const recoveryService=new RecoveryService({campaignRepo,checkpointService,queueService,logRepo});const analyticsService=new AnalyticsService({campaignRepo,logRepo,serverRepo});const ctx={config,db,serverRepo,memberRepo,campaignRepo,checkpointRepo,logRepo,serverService,memberService,checkpointService,campaignService,queueService,recoveryService,analyticsService,logger,settings:await db.read('settings.json')};
 const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers]});const commands=loadCommands();ctx.client=client;client.once('ready',()=>require('./events/ready')(client,ctx).catch(e=>logger.error('Ready handler failed',{error:e.message})));client.on('guildCreate',g=>require('./events/guildCreate')(g,ctx).catch(e=>logger.error('Guild registration failed',{error:e.message})));client.on('interactionCreate',i=>require('./events/interactionCreate')(i,ctx,commands));
 const app=createDashboard(ctx);const http=app.listen(config.port,()=>logger.info('Dashboard listening',{port:config.port}));let shutting=false;async function shutdown(signal){if(shutting)return;shutting=true;logger.info('Graceful shutdown requested',{signal});queueService.requestShutdown();const deadline=Date.now()+10000;while((queueService.running||queueService.active.size)&&Date.now()<deadline)await new Promise(r=>setTimeout(r,100));http.close();client.destroy();logger.info('Shutdown complete');process.exit(0);}process.on('SIGINT',()=>shutdown('SIGINT'));process.on('SIGTERM',()=>shutdown('SIGTERM'));await client.login(config.discordToken);}
main().catch(e=>{logger.error('Fatal startup error',{error:e.message,stack:e.stack});process.exit(1);});
